### ISSUE TITLE
Rename rendering function!

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/altair#48]
Following [this suggestion](https://github.com/ijlyttle/altair/issues/15#issuecomment-386902591) from @AliciaSchep, I wonder if we should rename the rendering function `vegalite()` to `vegawidget()`? Other ideas? Leave it as-is?

@AliciaSchep suggests that this rendering function, and friends, could be split off into its own package **vegawidget** that would render all manner of Vega and Vega-Lite specifications.

**Comment by g3o2** [comment]
Why not name the function after the already familiar `vega_embed`? `vega_widget` would be a good name for a helper function. 

Given the `$schema` property, vega-embed 3 automatically recognizes vega3/4/... and vega-lite2/... specs. So `vega-lite()` as a render function would no longer be needed.

**Comment by AliciaSchep** [comment]
I like the idea of also naming the main render function `vegawidget` (or `vega_widget`).  I see `widget` as referring to the fact that the function is creating an htmlwidget, which is a higher level thing than just `vega_embed` in R terms.  Since the function could also take in `vega` specs in addition to `vegalite` specs, the name `vegalite` would be less appropriate.

**Comment by ijlyttle** [comment]
Going on my to-do list! `vegalite()` will be deprecated in favor of `vegawidget()`. If (when) this becomes its own package, I think it would be useful to have the package name to be the same as the function name.
